version: '3.1'

services:
  db:
    image: postgres
    container_name: db-sensors
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: sensors-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: sensors-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5000
    ports:
      - 3000:3000
    depends_on:
      - backend